# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T05:04:39+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class WellKnownMercurePostRequest(BaseModel):
    data: str = Field(..., description='The content of the new version of this topic.')
    id: Optional[str] = Field(
        None,
        description="The topic's revision identifier: it will be used as the SSE's `id` property.",
    )
    private: Optional[bool] = Field(
        None,
        description='To mark an update as private. If not provided, this update will be public.',
    )
    retry: Optional[int] = Field(
        None, description="The SSE's `retry` property (the reconnection time)."
    )
    topic: List[str] = Field(
        ...,
        description='IRIs of the updated topic. If this key is present several times, the first occurrence is considered to be the canonical URL of the topic, and other ones are considered to be alternate URLs.',
    )
    type: Optional[str] = Field(
        None, description="The SSE's `event` property (a specific event type)."
    )
